export const HOOK_TYPE_OPTIONS = [
  "desafiante",
  "fomo",
  "problema_dolor",
  "promesa_resultado",
  "comparacion",
  "historia",
  "resultados_cuantificables",
  "desafiar_creencias",
  "problema_insight",
  "declaracion_provocadora",
  "tecnico_educativo",
  "autenticidad",
  "cotilla",
  "formula",
  "hoyo",
  "negativo",
  "conexiones_discordantes",
  "reto",
  "sorpresa",
  "pregunta_inducida",
  "regla_de_3",
  "enemigo_comun",
  "contracorriente",
  "si_tu",
  "facto",
  "pregunta_incomoda",
  "sabias_que",
  "razones",
  "situaciones",
  "resultado",
  "otro",
] as const;

export function buildOutputContract() {
  return [
    "Responde exclusivamente con JSON valido.",
    "Usa exactamente estas claves: summary, strengths, weaknesses, improvements, topics, hooks, hookType, hookAssessment, confidence.",
    "summary debe ser un string de 1 o 2 parrafos.",
    "strengths, weaknesses, improvements, topics y hooks deben ser arrays de strings concretos.",
    "hookType debe ser uno de: " + HOOK_TYPE_OPTIONS.join(", ") + ".",
    "hookAssessment debe ser un string corto explicando si el hook funciona o no para esta pieza.",
    "confidence debe ser un numero entre 0 y 1.",
    "No uses markdown ni texto fuera del JSON.",
  ].join("\n");
}
